<a href="https://colab.research.google.com/github/PranavKathar/Spam-Classification/blob/main/Copy_of_ML_project_Bert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.5 MB 28.0 MB/s 
     |████████████████████████████████| 182 kB 61.1 MB/s 
     |████████████████████████████████| 7.6 MB 58.0 MB/s 


In [ ]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import pipeline
import numpy as np

In [ ]:
text = """Hello! Hope you are safe and doing well.

People are experiencing extreme inconvenience for finding and availing essential resources like PPE kits, medicines, ICU Beds, Oxygen etc. required to battle Covid-19 / related distress.
 
We observed that some of these problems are caused by
-  Fake/outdated/unverified information on social media forwards/posts 
-  Logistics inefficiency due to lack of reliable information.
-  Mismanagement of resources

Being individuals with engineering and entrepreneurial mindset, we came up with a solution:
CIMP - Centralized Inventory Management Platform.
A digital portal where, people can search for required resources near their location. 
Information on availability of the resources in various target operational areas will be stored on a centralized database, and will be continuously updated by a huge team of volunteers.

We are hoping to launch this platform very soon, but we need your help! To keep the platform functional and useful, we need a lot of volunteers and resources.

- Anyone can volunteer, no age limit/eligibility
- Certificates will be issued
- Get team work and leadership experience.
- No time constraints, less than 1 hour per day work would suffice

Please fill out this form if you are interested to volunteer with us for helping fellow humans, and convince your friends too
https://bitleaf.tech/cimp/volunteeringform.html 

Other than volunteering, we are also looking for help in terms of collaborations with various government, social and private organizations, and sponsorship.

More details on this project are available on our social media pages - 
Please follow us and share our posts so that we can reach more people and thus help more people.
https://instagram.com/cimp.help 
https://facebook.com/cimp.help  

We are also reachable via email - cimp.help@gmail.com | cimp.help@bitleaf.tech

Whatsapp:
Advait -  https://wa.me/918291184516?text=Hello,%20I%20wanted%20to%20discuss%20regarding%20CIMP%20Project.%20

Please share this message as much as possible with your friends, family and acquaintances. Thank you!
"""

In [ ]:
summarizer = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

In [ ]:
summarizer(text, max_length=100, min_length=30, do_sample=False)

[{'summary_text': ' CIMP - Centralized Inventory Management Platform . Centralized database will be continuously updated by a huge team of volunteers . We are hoping to launch this platform very soon, but we need your help!'}]

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning with Python/ML project - Sheet1.csv", names=["message", "label"])

In [ ]:
data

message  label
0    Hello! Hope you are safe and doing well.\n\nPe...    imp
1    "It's only in theatre that you live truly"\nHa...  unimp
2    Time has come to showcase some new talented fa...  unimp
3    Wrap your fingers around a set of these string...  unimp
4    The world moved from radio to Spotify but her ...  unimp
..                                                 ...    ...
98   ☢️💥✨💥☢️\nNuclear energy is the future of India...  unimp
99   All the world's a stage, awaiting to spectate,...  unimp
100  Think India VNIT Nagpur Chapter \n\nThink Indi...    imp
101  "It's only in theatre that you live truly"\nHa...  unimp
102  ❗❗❗RECREATIONAL CRICKET MATCH BETWEEN CHEMICAL...  unimp

[103 rows x 2 columns]

In [ ]:
X = list(data["message"])
y = list(data["label"])


In [ ]:

pd.get_dummies(y, drop_first=True)

unimp
0        0
1        1
2        1
3        1
4        1
..     ...
98       1
99       1
100      0
101      1
102      1

[103 rows x 1 columns]

In [ ]:

y = list(pd.get_dummies(y, drop_first=True)["unimp"])

In [ ]:
y

[0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1]

In [ ]:
print("uninportant=",sum(y), ", important=",len(y)-sum(y))

uninportant= 36 , important= 67


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

1) call the pretrained model
2) Call the tokenizer

In [ ]:
from transformers import DistilBertTokenizerFast
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

loading file vocab.txt from cache at /root/.cache/huggingface/hub/models--distilbert-base-uncased/snapshots/1c4513b2eedbda136f57676a34eea67aba266e5c/vocab.txt
loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--distilbert-base-uncased/snapshots/1c4513b2eedbda136f57676a34eea67aba266e5c/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--distilbert-base-uncased/snapshots/1c4513b2eedbda136f57676a34eea67aba266e5c/tokenizer_config.json
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--distilbert-base-uncased/snapshots/1c4513b2eedbda136f57676a34eea67aba266e5c/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert-base-uncased",
  "activation": "gelu",
  "architectures": [
    "DistilBertForMaskedLM"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropo

In [ ]:
train_encodings = tokenizer(X_train, truncation=True, padding=True)
test_encodings = tokenizer(X_test, truncation=True, padding=True)

In [ ]:
X_train[-1]

'‼️The last date to submit applications for fee remission will be extended as confirmed by the administration. The final date for submission of the applications will officially be declared tomorrow or day after.‼️'

In [ ]:
train_encodings[0]

Encoding(num_tokens=469, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [ ]:
train_encodings

3) Convert these encodings into dataset objects

In [ ]:
import tensorflow as tf
train_dataset = tf.data.Dataset.from_tensor_slices(
    (dict(train_encodings), y_train)
)
test_dataset = tf.data.Dataset.from_tensor_slices(
    (dict(test_encodings), y_test)
)

In [ ]:
train_dataset

<TensorSliceDataset element_spec=({'input_ids': TensorSpec(shape=(469,), dtype=tf.int32, name=None), 'attention_mask': TensorSpec(shape=(469,), dtype=tf.int32, name=None)}, TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [ ]:
from transformers import TFDistilBertForSequenceClassification, TFTrainer, TFTrainingArguments

In [ ]:
training_args = TFTrainingArguments(
    output_dir = "./results",
    num_train_epochs = 20,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    eval_steps = 1000
)

The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [ ]:
with training_args.strategy.scope():
  model = TFDistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased")
  
trainer = TFTrainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = test_dataset
)

Tensorflow: setting up strategy
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--distilbert-base-uncased/snapshots/1c4513b2eedbda136f57676a34eea67aba266e5c/config.json
Model config DistilBertConfig {
  "activation": "gelu",
  "architectures": [
    "DistilBertForMaskedLM"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.24.0",
  "vocab_size": 30522
}

loading weights file tf_model.h5 from cache at /root/.cache/huggingface/hub/models--distilbert-base-uncased/snapshots/1c4513b2eedbda136f57676a34eea67aba266e5c/tf_model.h5
Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertFo

In [ ]:
trainer.evaluate(test_dataset)

***** Running Evaluation *****
  Num examples in dataset = 21
  Num examples in used in evaluation = 32
  Batch size = 16
{'eval_loss': 0.6901383996009827, 'epoch': 0, 'step': 0}


{'eval_loss': 0.6901383996009827}

In [ ]:
trainer.train()

***** Running training *****
  Num examples = 82
  Num Epochs = 20.0
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Steps per epoch = 11
  Total optimization steps = 220
{'loss': 0.6952249, 'learning_rate': 1e-06, 'epoch': 0.9090909090909091, 'step': 10}
{'loss': 0.6836141, 'learning_rate': 2e-06, 'epoch': 1.8181818181818183, 'step': 20}
{'loss': 0.65848315, 'learning_rate': 2.9999999e-06, 'epoch': 2.7272727272727275, 'step': 30}
{'loss': 0.64053494, 'learning_rate': 4e-06, 'epoch': 3.6363636363636362, 'step': 40}
{'loss': 0.6110695, 'learning_rate': 5.0000003e-06, 'epoch': 4.545454545454545, 'step': 50}
{'loss': 0.57153857, 'learning_rate': 5.9999998e-06, 'epoch': 5.454545454545454, 'step': 60}
{'loss': 0.4710087, 'learning_rate': 6.9999996e-06, 'epoch': 6.363636363636363, 'step': 70}
{'loss': 0.45735145, 'learning_rate': 8e-06, 'epoch': 7.2727272727272725, 'step': 80}
{'loss': 0.3134

In [ ]:
trainer.evaluate(test_dataset)

***** Running Evaluation *****
  Num examples in dataset = 21
  Num examples in used in evaluation = 32
  Batch size = 16
{'eval_loss': 0.10293973982334137, 'epoch': 20.0, 'step': 220}


{'eval_loss': 0.10293973982334137}

In [ ]:
trainer.predict(test_dataset)

***** Running Prediction *****
  Num examples in dataset = 21
  Batch size = 16


PredictionOutput(predictions=array([[-1.6293945 ,  1.4305569 ],
       [ 1.8016466 , -2.4889817 ],
       [-2.5161402 ,  2.4264455 ],
       [-2.4685004 ,  2.3310432 ],
       [ 2.2663362 , -2.875405  ],
       [ 2.3414023 , -2.9635777 ],
       [ 0.64360756, -0.9967012 ],
       [ 2.3341184 , -2.961682  ],
       [ 2.4070551 , -2.9925897 ],
       [-2.4774833 ,  2.409331  ],
       [ 2.2847896 , -2.91598   ],
       [ 0.3086686 , -0.74583244],
       [ 0.88652664, -1.3751416 ],
       [-2.286923  ,  2.1700392 ],
       [-2.4685004 ,  2.3310432 ],
       [ 2.3778696 , -3.0092263 ],
       [-2.4421468 ,  2.3421633 ],
       [ 2.3811574 , -3.0273519 ],
       [-2.3812633 ,  2.3138006 ],
       [-2.3109546 ,  2.1811886 ],
       [ 2.1771696 , -2.8535552 ]], dtype=float32), label_ids=array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
      dtype=int32), metrics={'eval_loss': 0.09674284607172012})

In [ ]:
output = trainer.predict(test_dataset)

***** Running Prediction *****
  Num examples in dataset = 21
  Batch size = 16


In [ ]:
pred = np.argmax(output.predictions, axis=-1)

In [ ]:
pred

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0])

In [ ]:
output.label_ids

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
      dtype=int32)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test, pred)

In [ ]:
cm

array([[11,  0],
       [ 1,  9]])

In [ ]:
trainer.save_model("/content/drive/MyDrive/Machine Learning with Python/imp_unimp_model")

Saving model in /content/drive/MyDrive/Machine Learning with Python/imp_unimp_model
Configuration saved in /content/drive/MyDrive/Machine Learning with Python/imp_unimp_model/config.json
Model weights saved in /content/drive/MyDrive/Machine Learning with Python/imp_unimp_model/tf_model.h5


In [ ]:
with training_args.strategy.scope():
  model = TFDistilBertForSequenceClassification.from_pretrained("/content/drive/MyDrive/Machine Learning with Python/imp_unimp_model")

loading configuration file /content/drive/MyDrive/Machine Learning with Python/imp_unimp_model/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert-base-uncased",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.24.0",
  "vocab_size": 30522
}

loading weights file /content/drive/MyDrive/Machine Learning with Python/imp_unimp_model/tf_model.h5
Some layers from the model checkpoint at /content/drive/MyDrive/Machine Learning with Python/imp_unimp_model were not used when initializing TFDistilBertForSequenceClassification: ['dropout_39']
- This IS expected if you ar

In [ ]:
example = "Let's go to aarohi"
example_encodings = tokenizer([example], truncation=True, padding=True)
example_dataset = tf.data.Dataset.from_tensor_slices((dict(example_encodings),[0]))

In [ ]:
a = model.predict(example_dataset)

1/1 [==============================] - 0s 85ms/step


In [ ]:
res = np.argmax(a.logits)
if res==0:
  print("This message is IMPORTANT!")
else:
  print("This message is not important")

This message is not important
